name: '16 - Working with Environments'

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: 'The environment to deploy to'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    if: inputs.environment == 'prod'
    
    steps:
      - name: E2E tests
        run: echo "Running E2E tests"

  deploy:
    runs-on: ubuntu-latest
    if: always()
    needs: e2e-tests
    environment: ${{ inputs.environment }}
    env:
      my-env-value: ${{ vars.MY_ENV_VALUE || 'default value' }}
    
    steps:
      - name: Deploy
        run: echo "Deploying to ${{ inputs.environment }}"